/*****************
 * 
 * Name         :       Constants
 * Description  :       This will have value of variable will be used in various class or any error message
 *                      so that common variable is used every where and easy to manage
 * 
 *****/
public class Constants {


    /****** ERROR Message Variables ****/
    public Static string NO_ACCOUNT_PASSED = 'NO Account passed for Duplicate Rules';
    public Static string NO_RECORD_PASSED = 'NO Record passed for Duplicate Rules';
    public Static string INCORRECT_FIELD_SET = 'This Field Set Does Not Exist, Please Pass Correct Field Set Name.';

}