@isTest
private class CustomerResponse_Test {

    static testMethod void CustomerResponse_method() {
    CustomerResponse.Customers customer = new CustomerResponse.Customers();
    customer.CustomerId ='';
    customer.Email ='';
    customer.Title ='';
    customer.FirstName = '';
    customer.LastName = '';
    customer.CountryCode='';
    customer.PostCode='';
    customer.Address ='';
    customer.City ='';
    customer.County ='';
    customer.HomeTel ='';
    customer.MobileTel ='';
    customer.Notes='';
    customer.LoyaltyId='';
    customer.Nationality='';
    customer.SendTextAlerts = false;
    customer.EmailSignup = false;
    customer.CultureCode='';
    customer.Created='';
   
    
    }
    
}