public class GDPRConstant {

   public static final string GDPR_SELECTED_STATUS_NOT_STARTED = 'Not started'; 
   public static final string GDPR_SELECTED_STATUS_COMPLETE = 'Completed';
   public static final string GDPR_SELECTED_STATUS_ERROR = 'Error';
   public static final string GDPR_SELECTED_STATUS_VALIDATED = 'Validated';
   public static final string GDPR_CHILD_QUERY_STATUS_NEW = 'New';
   public static final string GDPR_CHILD_QUERY_STATUS_COMPLETE = 'Complete';
   public static final string GDPR_CHILD_QUERY_STATUS_FAILED = 'Failed';
   public static final string GDPR_CHILD_QUERY_STATUS_VALIDATED = 'Validated';
   public static final string GDPR_CHILD_QUERY_STATUS_PASSED = 'Passed';

}